### PR TITLE
Improved README

### LINKED ISSUE #4: update readme file
update the readme file .
add some decoration and description to it

### PR DESCRIPTION
**Pull request by hizkifw**
fixes #4

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @HizkiFW

**Comment by srbcheema1** [comment]
@HizkiFW 
you have done a awesome work 
i would be glad if you would contribute to my other repositories also
and dont forget to give STAR to them

**Comment by hizkifw** [comment]
@srbcheema1 I'd love to, but I want to help others as well. Just drop me a message if you need help. I'd be glad to contribute more!

**Comment by srbcheema1** [comment]
that great :)

**Pull request merged**
